# Generated by Django 2.0 on 2021-09-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(default='asd#45', max_length=150)),
                ('Lname', models.CharField(default='lname', max_length=255)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Mobile', models.IntegerField(default='456')),
                ('Address', models.CharField(default='address', max_length=255)),
                ('Password', models.CharField(default='password', max_length=255)),
                ('OTP', models.IntegerField(default=0)),
            ],
        ),
    ]
